# Generated by Django 4.0.1 on 2022-08-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='handlers',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='name',
        ),
    ]
