# Generated by Django 4.0.1 on 2022-08-23 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0002_remove_schedule_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='qualified_handlers',
        ),
        migrations.AddField(
            model_name='task',
            name='qualified_members',
            field=models.ManyToManyField(blank=True, related_name='task_qualifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
