# Generated by Django 4.0.1 on 2022-08-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_remove_task_qualified_handlers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='display_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_sub_category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
