# Generated by Django 4.0.1 on 2022-09-11 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_task_display_name_alter_task_task_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scheduling.schedule'),
            preserve_default=False,
        ),
    ]
