# Generated by Django 4.0.1 on 2022-10-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_remove_schedule_tasks_task_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Handler',
        ),
    ]
