# Generated by Django 4.0.1 on 2022-04-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_client_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
            ],
        ),
    ]
