# Generated by Django 4.0.1 on 2022-07-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_plan_plan_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_data',
            field=models.JSONField(default=dict),
        ),
    ]
