# Generated by Django 4.0.1 on 2022-07-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_dish_description'),
        ('main', '0004_alter_plan_plan_data_alter_plan_possible_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='possible_meals',
            field=models.ManyToManyField(blank=True, to='nutrition.Dish'),
        ),
    ]
