# Generated by Django 4.0.1 on 2022-07-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_plan_possible_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
