# Generated by Django 4.0.1 on 2022-07-17 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_client_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_alter_plan_plan_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='assigned_users',
            field=models.ManyToManyField(through='main.PlanAccess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planaccess',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='main.plan'),
        ),
        migrations.AddField(
            model_name='planaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to=settings.AUTH_USER_MODEL),
        ),
    ]
