# Generated by Django 4.0.1 on 2022-07-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_planaccess_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planaccess',
            name='admin',
        ),
        migrations.AddField(
            model_name='planaccess',
            name='level',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('OWNER', 'Owner')], default='USER', max_length=10),
        ),
    ]
