# Generated by Django 4.0.1 on 2022-08-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_plan_plan_maker_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(default='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
