# Generated by Django 4.0.1 on 2022-08-06 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
        ('main', '0011_plan_description_alter_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_route',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='routing.route'),
        ),
    ]
