# Generated by Django 4.0.1 on 2022-08-07 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_alter_route_end_location_and_more'),
        ('scheduling', '0001_initial'),
        ('main', '0012_plan_plan_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scheduling.schedule'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_route',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='routing.route'),
        ),
    ]
