# Generated by Django 4.0.1 on 2022-08-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_plan_plan_schedule_alter_plan_plan_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='possible_meals',
        ),
    ]
