# Generated by Django 4.0.1 on 2022-08-30 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0010_menu'),
        ('main', '0014_remove_plan_possible_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_meal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nutrition.menu'),
        ),
    ]
