# Generated by Django 4.0.1 on 2022-09-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_plan_plan_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='sharing_status',
            field=models.CharField(default='PUBLIC_END', max_length=100),
        ),
    ]
