# Generated by Django 4.0.1 on 2022-10-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_plan_plan_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_maker_progress',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
