# Generated by Django 4.0.1 on 2022-08-06 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='end_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_ends', to='routing.location'),
        ),
        migrations.AlterField(
            model_name='route',
            name='expected_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='expected_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_starts', to='routing.location'),
        ),
    ]
