# Generated by Django 4.0.1 on 2022-05-29 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_in_grams', models.FloatField(null=True)),
                ('price_per_gram', models.FloatField(null=True)),
                ('validity', models.BooleanField(default=None, null=True)),
                ('extra_info', models.JSONField(null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrition.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_in_grams', models.FloatField(null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrition.dish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrition.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='recipe_ingredient',
            field=models.ManyToManyField(through='nutrition.DishIngredient', to='nutrition.Ingredient'),
        ),
    ]
