# Generated by Django 4.0.1 on 2022-05-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_per_gram',
            new_name='total_price',
        ),
    ]
