# Generated by Django 4.0.1 on 2022-05-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_rename_price_per_gram_product_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='validity',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
