# Generated by Django 4.0.1 on 2022-06-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_alter_dishingredient_dish_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'dishes'},
        ),
        migrations.RemoveField(
            model_name='dish',
            name='validity',
        ),
        migrations.RemoveField(
            model_name='dishingredient',
            name='validity',
        ),
    ]
