# Generated by Django 4.0.1 on 2022-06-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_mealtype_dish_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
