# Generated by Django 4.0.1 on 2022-08-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_dish_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('meal_times', models.JSONField(blank=True, default=list, null=True)),
                ('last_solutions', models.JSONField(blank=True, default=dict, null=True)),
                ('possible_meals', models.ManyToManyField(blank=True, to='nutrition.Dish')),
            ],
            options={
                'verbose_name_plural': 'Menus',
            },
        ),
    ]
