# Generated by Django 4.0.1 on 2022-10-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0012_menu_product_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_info_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
